/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_umeng_soexample_Jni */

#ifndef _Included_com_umeng_soexample_Jni
#define _Included_com_umeng_soexample_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_umeng_soexample_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_umeng_soexample_Jni_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
