/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myselfapp_JniUtils */

#ifndef _Included_com_example_myselfapp_JniUtils
#define _Included_com_example_myselfapp_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myselfapp_JniUtils
 * Method:    getMyName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myselfapp_JniUtils_getMyName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
